name: CI Tests

on:
  push:
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1.0.2
    with:
      display: true
      coverage: codecov
      fail-fast: true
      libraries: |
        apt:
          - libxkbcommon-x11-0
          - libxcb-icccm4
          - libxcb-image0
          - libxcb-keysyms1
          - libxcb-randr0
          - libxcb-render-util0
          - libxcb-xfixes0
          - libxcb-xinerama0

      envs: |
        # Code style
        - linux: codestyle

        # Standard tests
        - linux: py36-test
        - linux: py37-test
        - linux: py38-test
        - linux: py39-test
        - linux: py310-test

        - macos: py36-test
        - macos: py37-test
        - macos: py38-test
        - macos: py39-test

        - windows: py37-test
        - windows: py38-test
        - windows: py39-test

  allowed_failures:
    # Tests allowed to fail (will not trigger cancellation of all in-progress jobs)
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1.0.2
    with:
      display: true
      fail-fast: false
      envs: |
        # UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 14099-14100: invalid continuation byte
        - windows: py36-test
        # FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
        - windows: py310-test
        # OSError: Could not find library geos_c or load any of its variants
        - macos: py310-test
